---
- name: Undeploys "{{ context_name }}"
  shell: wget --http-user={{ admin_user }} --http-password={{ admin_password }}  "{{ tomcat_manager_url }}/text/undeploy?path=/{{ context_name }}" -O -
  ignore_errors: yes
  register: wget

- debug: 
    msg: "Undeploying result {{ wget.stdout }}. "

- name: Deploys "{{ context_name }}"
  shell: wget --http-user={{ admin_user }} --http-password={{ admin_password }} "{{ tomcat_manager_url }}/text/deploy?path=/{{ context_name }}&war=file:/{{ tomcat_path }}/artifacts/{{ artifact_name }}" -O -
  register: wget

- debug: 
    msg: "Deploying result {{ wget.stdout }}. "