# --extra-vars "artifact_path=/path/foo"
---
- hosts: portal
  remote_user: web

  vars:
    artifact_name: admprf
    context_name: admprf
    source_folder_name: dist

  roles:
  - role: create-artifact-folder
  - role: copy-artifact-folder
  - role: undeploy-deploy-artifact
