# --extra-vars "artifact_path=/path/foo"
---
- hosts: cashbids-apis
  remote_user: web

  vars:
    artifact_name: dtnportal-cashbids-api
    microservice_folder: cashbids
    microservice_port: 8093
    
  roles:
  - role: copy-microservice
  - role: restart-microservice
