# --extra-vars "artifact_path=/path/foo"
---
- hosts: portal
  remote_user: web

  vars:
    artifact_name: micro-auth
    microservice_folder: auth
    

  roles:
  - role: copy-microservice
  - role: restart-microservice