# --extra-vars "artifact_path=/path/foo"
---
- hosts: accounts-apis
  remote_user: web

  vars:
    artifact_name: dtnportal-accounts-api
    microservice_folder: accounts
    microservice_port: 8095
    
  roles:
  - { role: copy-microservice, tags: [ 'copy' ]}
  - { role: restart-microservice, tags: [ 'restart' ]}
