# --extra-vars "artifact_path=/path/foo"
---
- hosts: apis
  remote_user: web

  vars:
    artifact_name: dtnportal-oms-api
    microservice_folder: oms
    microservice_port: 8094
    
  roles:
  - role: copy-microservice
  - role: restart-microservice
