--- 
- name: Creating the artifacts folder
  shell: mkdir {{ tomcat_path }}/artifacts
  ignore_errors: yes
  notify: delete artifact

- name: Copying the "{{ artifact_name }}" into the server
  copy: src={{ artifact_path }}/{{ artifact_name }} dest={{ tomcat_path }}/artifacts/{{ artifact_name }}
  when: artifact_path is defined

- name: Undeploying "{{ context_name }}"
  shell: wget --http-user={{ admin_user }} --http-password={{ admin_password }}  "{{ tomcat_manager_url }}/text/undeploy?path=/{{ context_name }}" -O -
  ignore_errors: yes
  register: wget

- debug: 
    msg: "Undeploying result {{ wget.stdout }}. "

- name: Deploying "{{ context_name }}"
  shell: wget --http-user={{ admin_user }} --http-password={{ admin_password }} "{{ tomcat_manager_url }}/text/deploy?path=/{{ context_name }}&war=file:/{{ tomcat_path }}/artifacts/{{ artifact_name }}" -O -
  register: wget
  notify: delete artifact

- debug: 
    msg: "Deploying result {{ wget.stdout }}. "
