--- 
- name: Creates "artifacts" folder
  file:
    path: "{{ tomcat_path }}/artifacts"
    state: directory
  ignore_errors: yes
- name: Deletes the previous artifact
  file:
    path: "{{ tomcat_path }}/artifacts/{{ artifact_name }}"
    state: absent
  ignore_errors: yes