--- 
- name: Restarting {{ artifact_name }} service
  shell: nohup {{ microservices_path }}/{{ microservice_folder}}/{{ artifact_name }}.sh restart
  register: out
  changed_when: false

- debug:
    msg: "{{ out.stdout }}"

- name: wait
  wait_for: port={{ microservice_port }} delay=1